name: image_gallery_saver_plus
description: A Flutter plugin to save images to the gallery with null safety support.
version: 3.0.5
homepage: https://github.com/hui-n/flutter_image_gallery_saver

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.image_gallery_saver_plus
        pluginClass: ImageGallerySaverPlusPlugin
      ios:
        pluginClass: ImageGallerySaverPlugin 